image: "ruby:2.5"

before_script:
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

variables:
  REDIS_URL: "redis://redis"
  SIDEKIQ_VERSION_FOR_TESTS: '~> 5.0'

rspec:
  stage: test
  coverage: '/LOC \((\d+\.\d+%)\) covered.$/'
  script:
    - bundle exec rspec
  services:
    - redis:alpine
  artifacts:
    expire_in: 31d
    when: always
    paths:
      - coverage/

.integration:
  stage: test
  script:
    - cd tests/reliability
    - bundle exec ruby reliability_test.rb
  services:
    - redis:alpine

integration_semi:
  extends: .integration
  variables:
    JOB_FETCHER: semi

integration_reliable:
  extends: .integration
  variables:
    JOB_FETCHER: reliable

integration_basic:
  extends: .integration
  allow_failure: yes
  variables:
    JOB_FETCHER: basic

kill_interruption:
  stage: test
  script:
    - cd tests/interruption
    - bundle exec ruby test_kill_signal.rb
  services:
    - redis:alpine

term_interruption:
  stage: test
  script:
    - cd tests/interruption
    - bundle exec ruby test_term_signal.rb
  services:
    - redis:alpine

.sidekiq_6_1:
  variables:
    SIDEKIQ_VERSION_FOR_TESTS: '>= 6.1'

rspec_for_sidekiq_6:
  extends:
    - rspec
    - .sidekiq_6_1

integration_semi_for_sidekiq_6:
  extends:
    - integration_semi
    - .sidekiq_6_1

integration_reliable_for_sidekiq_6:
  extends:
    - integration_reliable
    - .sidekiq_6_1

integration_basic_for_sidekiq_6:
  extends:
    - integration_basic
    - .sidekiq_6_1

kill_interruption_for_sidekiq_6:
  extends:
    - kill_interruption
    - .sidekiq_6_1

term_interruption_for_sidekiq_6:
  extends:
    - term_interruption
    - .sidekiq_6_1

# rubocop:
#   script:
#     - bundle exec rubocop
